import React from "react";
import { Composition } from "remotion";
import { Gpt6SolanaPromo } from "./Composition";
import { DynamicComposition } from "./DynamicComposition";
import { GeneratedVideo } from "./generated/GeneratedVideo";
import { VoxGeneratedVideo } from "./vox/VoxGeneratedVideo";
import { LongFormComposition } from "./vox/LongFormComposition";
import { MinoShortsComposition } from "./vox/mino/MinoShortsComposition";
import defaultProps from "./dynamic-props.json";
import voxMeta from "./vox/vox-meta.json";
import longformMeta from "./vox/longform-meta.json";
import stockMeta from "./stock/stock-meta.json";
import { StockVideoComposition } from "./stock/StockVideoComposition";

export const Root: React.FC = () => {
  const voxFrames = Math.max(90, Math.ceil((voxMeta.durationSeconds || 10) * 30));
  const longformFrames = Math.max(90, longformMeta.totalFrames || 1800);
  const stockFrames = Math.max(90, stockMeta.durationFrames || 180);
  const stockWidth = stockMeta.width || 3840;
  const stockHeight = stockMeta.height || 2160;

  return (
    <>
      {/* 0. Vox Shorts 9:16 Vertical Video with Character Mino */}
      <Composition
        id="MinoShorts"
        component={MinoShortsComposition}
        durationInFrames={voxFrames}
        fps={30}
        width={1080}
        height={1920}
      />

      {/* 1. Long-Form Modular Documentary Video (Multi-Chapter via <Series>) */}
      <Composition
        id="LongFormVideo"
        component={LongFormComposition}
        durationInFrames={longformFrames}
        fps={30}
        width={1920}
        height={1080}
      />

      {/* 2. Autonomous Vox-Style Video Generated by GPT-6.1 Sol per audio */}
      <Composition
        id="VoxVideo"
        component={VoxGeneratedVideo}
        durationInFrames={voxFrames}
        fps={30}
        width={1920}
        height={1080}
      />

      {/* 3. Autonomous React Code Generated by GPT-6.1 Sol from prompt */}
      <Composition
        id="AutonomousVideo"
        component={GeneratedVideo}
        durationInFrames={300}
        fps={30}
        width={1920}
        height={1080}
      />

      {/* 4. Structured JSON Driven Dynamic Composition */}
      <Composition
        id="AutoGpt6Video"
        component={DynamicComposition}
        durationInFrames={300}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={defaultProps}
      />

      {/* 5. Static Default Composition */}
      <Composition
        id="Gpt6SolanaPromo"
        component={Gpt6SolanaPromo}
        durationInFrames={300}
        fps={30}
        width={1920}
        height={1080}
      />

      {/* 6. Stock Footage 5-6s Seamless Loop for Adobe Stock & Shutterstock */}
      <Composition
        id="StockVideo"
        component={StockVideoComposition}
        durationInFrames={stockFrames}
        fps={30}
        width={stockWidth}
        height={stockHeight}
      />
    </>
  );
};
